version: 2
jobs:
  build:
    working_directory: ~/circleci-alationTestA
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: |
          mvn clean install