version: 2
jobs:
  build:
    working_directory: ~/circleci-alationTestA
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: |
          mvn clean install
          git checkout master
          git pull
          git checkout develop
          git pull
          git rebase -i master
          git checkout master
          git merge develop